### PR TITLE
Python 3

### PR DESCRIPTION
**Pull request by nim65s**
Hi,

This PR allows Python 3 compatibility, and includes some major cleanups.
It requires https://github.com/jrl-umi3218/jrl-cmakemodules/pull/241.

Here is the result: https://gepgitlab.laas.fr/gsaurel/dynamic-graph-python/pipelines/6132/builds

### CODE REVIEW

**Comment by olivier-stasse** [comment]
Dear @nim65s could you elaborate on the solution you are proposing to replace the embedded interpreter ?

**Comment by nim65s** [comment]
Hi,

I was pretty sure we already discussed about that and we agreed that this was no longer useful. But in case I'm wrong, can you show me an example of where it is actually used ? Because I have no clue.

**Comment by MaximilienNaveau** [comment]
It is used in the dynamic_graph_bridge in order to interact with the graph. Typically on the robot we interact with this python interpretor using ROS service. The famous: `rosrun dynamic_graph_bridge run_command`. It allows us to connect the c++ of the graph with the c++ of the robot while using python for the control graph instanciation. I am sure Olivier can draw you a nice picture on how this works.

BTW: I also use it in the code I have in Tuebingen ;) If you guys decide to remove it I will have to implement a new one anyway.

**Comment by olivier-stasse** [comment]
Well currently it used everyday by the Gepetto team interacting with the robots. The integration tests are based on the interpreter. So we may have not stated this clearly, sorry the misunderstanding.
See https://gepgitlab.laas.fr/pyrene-dev/pyrene_integration_tests/blob/master/scripts/test_kine.py for instance.

**Comment by nim65s** [comment]
Ok, I'll reopen :)

**Pull request closed without merging**
