### PR TITLE
Release/4.0.0

### PR DESCRIPTION
**Pull request by nim65s**
Follows https://github.com/stack-of-tasks/dynamic-graph/pull/78

### CODE REVIEW

**Comment by nim65s** [comment]
I think `dgpyError` removal is an API break. So we should either increment the major version number, or provide a dummy replacement. What do you prefer, @jmirabel ?

**Comment by jmirabel** [comment]
I did not fully understand the reason for having them. What were they used for ?

**Comment by nim65s** [comment]
Having custom exceptions helps the user to understand the source of the issue he currently has, and the developer to raise / catch more precisely what he needs.

But looking at the code base, it doesn't seems to be used at all.

@MaximilienNaveau : do you use `dgpyError` / `error_out()` anywhere ?

**Comment by jmirabel** [comment]
> Having custom exceptions helps the user to understand the source of the issue he currently has, and the developer to raise / catch more precisely what he needs.

When standard exception matches the meaning, I think they are more suited. The error message is more important than the error type.

**Comment by MaximilienNaveau** [comment]
> Having custom exceptions helps the user to understand the source of the issue he currently has, and the developer to raise / catch more precisely what he needs.
> 
> But looking at the code base, it doesn't seems to be used at all.
> 
> @MaximilienNaveau : do you use `dgpyError` / `error_out()` anywhere ?

I think we do not

**Comment by nim65s** [comment]
@jmirabel : could you review 35f3a25 please ? Something like this is required for https://github.com/loco-3d/sot-talos-balance/pull/14

**Comment by nim65s** [comment]
Also, I still think we should increase the major version number.
Because other projects that were building fine with 3.5.3 will not build at all without modifications when we'll merge this PR.

**Comment by jmirabel** [comment]
> @jmirabel : could you review [35f3a25](https://github.com/stack-of-tasks/dynamic-graph-python/commit/35f3a2540d29da7244bab279a4e0fce205c60188) please ? Something like this is required for [loco-3d/sot-talos-balance#14](https://github.com/loco-3d/sot-talos-balance/pull/14)

Ideally, I would prefer users to include Pinocchio before, if needed. However, I also understand this makes things easier and safer.

> Also, I still think we should increase the major version number.

I am fine with increasing it.

**Comment by nim65s** [comment]
Well, they can't include anything before: the compiled file is https://github.com/jrl-umi3218/jrl-cmakemodules/blob/topic/dynamic_graph_cpp11/dynamic_graph/python-module-py.cc.in

**Comment by jmirabel** [comment]
There are many places where I do not use this file, e.g. in sot-core.

This is mandatory If you want to bind functions without using commands.

**Comment by nim65s** [comment]
If I test this on Ubuntu 16.04: a70f75fb6ac237ad45cabaa2fd0b13fead40d7b0

But as our TALOS is going to be upgraded to 16.04, we could start dropping 16.04 support, and add 20.04 instead.

@MaximilienNaveau : would this be OK for you ?

Otherwise, we'll have to workaround the lack of `bp::raw_function` in Boost 1.58 on 16.04 (and maybe other things…)

**Comment by MaximilienNaveau** [comment]
We are dropping 16.04 currently so all good to me. I am upgrading all our packages to ROS2 as well.

**Pull request merged**
