### PR TITLE
Switch to Boost Python

### PR DESCRIPTION
**Pull request by jmirabel**
Follows https://github.com/stack-of-tasks/dynamic-graph/pull/71

### CODE REVIEW

**Comment by jmirabel** [comment]
I added the switch to Boost Python in this PR.

**Comment by jmirabel** [comment]
First of all, this requires C++ 11 (although not stated anywhere).

It's not completely backward compatible but the amount of changes to adapt the code is minimal. Some which I can think of:
- `dg.entity.Entity.entities` is not a Python map anymore, but a C++ wrapper that mimics Python map. Iterating other it is done with `for k, v in dg.entity.Entity.entities` without the `.items` in the end (although it could be added...),
- calls to low-level function on entities and signals disappeared.
- commands added dynamically are not exposed. It is doable. I don't know if it is used anywhere.

I am sure there are others.

**Comment by nim65s** [comment]
Thanks @jmirabel for this work on the foundations of this package. I think we need a roadmap to merge this.

First, this PR requires https://github.com/stack-of-tasks/dynamic-graph/pull/71 ; but does it make sense to merge https://github.com/stack-of-tasks/dynamic-graph/pull/71 and release dynamic graph without this PR ?

**Comment by jmirabel** [comment]
Without commit 3eef956, this PR should be independant of stack-of-tasks/dynamic-graph#71. And actually, if we switch to boost-python, simplifications made in stack-of-tasks/dynamic-graph#71 could be even more simplified.


> I think we need a roadmap to merge this.

I think so too.

**Comment by jmirabel** [comment]
I rebased onto the recent changes and pushed this to branch cpp11.

**Pull request closed without merging**
