### PR TITLE
CMake exports

### PR DESCRIPTION
**Pull request by olivier-stasse**
Implements new cmake exports.
Add also new travis commands to have it work on github.
Gepgitlab is still the preferred way to test until push action is implemented.

### CODE REVIEW

**Comment by jmirabel** [comment]
Could you rebase and squash the two commits that cancels themselves ?
They will pollute the history for no reason.

**Comment by olivier-stasse** [comment]
@jmirabel I edited the history.
Could you confirm that this fine with you ?
@nim65s what do you think ?

**Comment by nim65s** [comment]
Tests are not passing without installation, and there is an link issue on stretch. I'll handle that.

**Comment by nim65s** [comment]
And the merge at the middle break things without explanations. I'll close this PR, and open a new one, with only the commits that actually deal with CMake Exports.

**Pull request closed without merging**
