### PR TITLE
Add fwd.hh header file.

### PR DESCRIPTION
**Pull request by florent-lamiraux**

### CODE REVIEW

**Comment by nim65s** [comment]
Hi,

I agree with this, but this will have to wait for a release of dynamic-graph with https://github.com/stack-of-tasks/dynamic-graph/pull/87 to be merged

**Comment by florent-lamiraux** [comment]
> Hi,
> 
> I agree with this, but this will have to wait for a release of dynamic-graph with [stack-of-tasks/dynamic-graph#87](https://github.com/stack-of-tasks/dynamic-graph/pull/87) to be merged

Why do we need a release to merge in branch `devel` ?. From my undestanding, `devel` branches should be compatible and releases should be compatible, but it is not possible to make compatible a combination of both.

**Comment by nim65s** [comment]
Devel branches of individual packages must be compatible with master branches of their dependencies, because the CI is set up with binary packages of the dependencies. As you can CI, the CI is not OK in this PR because:
```
In file included from /root/robotpkg/wip/py-dynamic-graph-v3/work/dynamic-graph-python-4.0.3/include/dynamic-graph/python/interpreter.hh:9:0,
from /root/robotpkg/wip/py-dynamic-graph-v3/work/dynamic-graph-python-4.0.3/src/interpreter.cc:12:
/root/robotpkg/wip/py-dynamic-graph-v3/work/dynamic-graph-python-4.0.3/include/dynamic-graph/python/fwd.hh:17:9: error: 'shared_ptr' does not name a type; did you mean 'char16_t'?
typedef shared_ptr<Interpreter> InterpreterPtr_t;
^~~~~~~~~~
```

I know you don't work like that in HPP, and therefore the CI is always broken in HPP, except just after a release… But please let's not have this kind of issues also in the SoT :)

**Comment by florent-lamiraux** [comment]
I understand. One solution would be to update `master` in `dynamic-graph`.

**Comment by nim65s** [comment]
What we actually need for gitlab-CI to work  is https://github.com/stack-of-tasks/dynamic-graph/pull/87 to be available in the binary package provided by robotpkg. This usually goes through a source release on the git project, and then publish this release on robotpkg.

But robotpkg is no longer our only way of distributing packages, so we should also publish that to ROS. By the way, I think we should also setup a ROS CI.

I'll handle those releases soon anyway. Do you have any particular deadline that I should be aware of to prioritize this correctly ?

**Comment by florent-lamiraux** [comment]
I have no particular deadline. Thank you.

**Pull request merged**
